# network architecture
# encoder related
stream: true
encoder: emformer
encoder_conf:
    chunk_length: 48
    subsampling_factor: 6
    d_model: 256    # dimension of attention
    nhead: 4
    dim_feedforward: 2048  # the number of units of position-wise feed forward
    num_encoder_layers: 12      # the number of encoder blocks
    dropout: 0.1
    layer_dropout: 0.075
    cnn_module_kernel: 31
    left_context_length: 48
    right_context_length: 12
    memory_size: 32


predictor_conf:
    predictor_dim: 512
    context_size: 2
joint_dim: 512

# hybrid CTC/attention
model_conf:
    ctc_weight: 0.3

dataset_conf:
    filter_conf:
        max_length: 40960
        min_length: 0
        token_max_length: 200
        token_min_length: 1
    resample_conf:
        resample_rate: 16000
    speed_perturb: true
    fbank_conf:
        num_mel_bins: 80
        frame_shift: 10
        frame_length: 25
        dither: 0.1
    spec_aug: true
    spec_aug_conf:
        num_t_mask: 5
        num_f_mask: 2
        max_t: 50
        max_f: 30
    shuffle: true
    shuffle_conf:
        shuffle_size: 1500
    sort: true
    sort_conf:
        sort_size: 500  # sort_size should be less than shuffle_size
    batch_conf:
        batch_type: 'dynamic' # static or dynamic
        # batch_size: 8
        max_frames_in_batch: 10000


grad_clip: 5
accum_grad: 4
max_epoch: 300
log_interval: 100

optim: adam
optim_conf:
    lr: 0.003

scheduler_conf:
    lr_batches: 5000
    lr_epochs: 6

warmup_steps: 3000
